#!/usr/bin/env bash

TMPFILE=repos.json

npm exec renovate -- --write-discovered-repos="${TMPFILE}"

filter_non_forks() {
  while read -r repo; do
    parent=$(curl -s -H "Authorization: token $SPECMATIC_GITHUB_TOKEN" \
      "https://api.github.com/repos/$repo" | jq -r '.parent.owner.login')
    if [[ -z "$parent" || "$parent" == "null" ]]; then
      echo "$repo"
    else
      echo "Skipping fork: $repo"
    fi
  done
}

jq -r '.[]' < "$TMPFILE" | grep -vE '(specmatic\.io)|(iata)|(^znsio/)'| filter_non_forks | xargs -P 5 -I {} bash -c "$@"
