/** @type {import("renovate/dist/config/types").AllConfig} */
module.exports = {
  $schema: "https://docs.renovatebot.com/renovate-schema.json",
  extends: [
    "config:recommended",
    "mergeConfidence:all-badges",
    "group:monorepos",
    "group:recommended",
    ":semanticCommitTypeAll(chore)",
    ":semanticCommitScope(deps)",
  ],
  addLabels: ["renovate", "dependency"],
  token: process.env.SPECMATIC_GITHUB_TOKEN,
  platform: "github",
  dependencyDashboard: true,
  osvVulnerabilityAlerts: true,
  dependencyDashboardOSVVulnerabilitySummary: "all",
  requireConfig: "optional",
  onboarding: false,
  cachePrivatePackages: true,
  gitIgnoredAuthors: ["renovate@whitesourcesoftware.com", "no-reply@specmatic.io"],
  gitAuthor: "Specmatic Renovate <github-service-account@specmatic.io>",
  ignorePrAuthor: true,
  autodiscover: true,
  autodiscoverFilter: [
    "specmatic/*",
  ],
  repositoryCache: "enabled",
  rebaseWhen: "conflicted",
  prFooter:
    "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate). Specmatic specific configuration is [managed here](https://github.com/specmatic/specmatic-renovate).",
  prHourlyLimit: 0,
  prConcurrentLimit: 0,
  packageRules: [
    {
      matchPackageNames: [
        "gradle",
        "org.assertj:*",
        "org.junit.jupiter:*",
        "org.junit.platform:*",
        "io.specmatic:*",
        "io.specmatic.*:*",
        "org.springframework.*:*",
        "jakarta.validation:*",
        "org.springdoc:*",
        "org.testcontainers:*",
        "com.fasterxml.jackson.*:*",
        "tools.jackson.*:*",
        "renovate",
        "com.squareup.okhttp3:*",
        "net.javacrumbs.json-unit:json-unit-assertj",
        "com.squareup.okio:*",
        "commons-io:commons-io",
        "org.apache.commons:*"
      ],
      matchUpdateTypes: [
        "minor",
        "patch"
      ],
      automerge: true,
    },
  ],
  vulnerabilityAlerts: {
    commitMessagePrefix: "[SECURITY] ",
    commitMessageSuffix: "",
    vulnerabilityFixStrategy: "lowest",
  },
  hostRules: [
    {
      hostType: "maven",
      matchHost: "repo.specmatic.io",
      username: process.env.SPECMATIC_REPOSILITE_USERNAME,
      password: process.env.SPECMATIC_REPOSILITE_TOKEN,
    },
  ],
  "packageGroups": [
    {
      groupName: "apache-curator",
      description: "Group updates for Apache Curator dependencies",
      matchPackageNames: [
        "org.apache.curator:**",
      ]
    },
    {
      groupName: "opensaml",
      description: "Group updates for OpenSAML",
      matchPackageNames: [
        "org.opensaml:**",
      ]
    },
    {
      groupName: "apache-kafka",
      description: "Group updates for Apache Kafka dependencies",
      matchPackageNames: [
        "org.apache.kafka:**",
      ]
    },
    {
      groupName: "jackson",
      description: "Group updates for Jackson dependencies",
      matchPackageNames: [
        "com.fasterxml.jackson.datatype:**",
        "com.fasterxml.jackson.dataformat:**",
        "com.fasterxml.jackson.core:**",
      ]
    },
    {
      groupName: "bouncycastle",
      description: "Group updates for bouncycastle",
      matchPackageNames: [
        "org.bouncycastle:**"
      ]
    }
  ]
};
