module.exports = {
  $schema: "https://docs.renovatebot.com/renovate-schema.json",
  extends: ["config:recommended", "mergeConfidence:all-badges"],
  token: process.env.GITHUB_TOKEN,
  // platform: "github",
  dependencyDashboard: true,
  osvVulnerabilityAlerts: true,
  dependencyDashboardOSVVulnerabilitySummary: "all",
  requireConfig: "optional",
  onboarding: false,
  autodiscover: true,
  cachePrivatePackages: true,
  autodiscoverFilter: [
    "znsio/specmatic-arazzo",
    "znsio/specmatic-async",
    "znsio/specmatic-google-pubsub",
    "znsio/specmatic-gradle-plugin",
    "znsio/specmatic-graphql",
    "znsio/specmatic-grpc",
    "znsio/specmatic-jdbc",
    "znsio/specmatic-jms",
    "znsio/specmatic-kafka",
    "znsio/specmatic-license",
    "znsio/specmatic-node",
    "znsio/specmatic-openapi",
    "znsio/specmatic-redis",
    "znsio/specmatic-renovate",
    "znsio/specmatic"
  ],
  repositoryCache: "enabled",
  prFooter:
    "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate). Specmatic specific configuration is [managed here](https://github.com/znsio/specmatic-renovate).",
  packageRules: [
    {
      matchPackageNames: ["gradle-wrapper"],
      automerge: true,
    },
  ],
  vulnerabilityAlerts: {
    dependencyDashboardApproval: false,
    commitMessagePrefix: "[SECURITY] ",
    commitMessageSuffix: "",
    vulnerabilityFixStrategy: "lowest",
  },
  prHourlyLimit: 5,
  hostRules: [
    {
      hostType: "maven",
      matchHost: "maven.pkg.github.com",
      username: "specmatic-builder",
      password: process.env.GITHUB_TOKEN,
    },
  ],
};
