#!/usr/bin/env bash

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

npm exec renovate -- --write-discovered-repos="${TMPFILE}"

jq -r '.[]' < "${TMPFILE}" | xargs -P 5 -I {} bash -c 'RENOVATE_AUTODISCOVER=false RENOVATE_REPOSITORIES={} FORCE_COLOR=3 npm exec renovate 2>&1 | sed "s!^![{}] !"'
